# Generated by Django 3.1.7 on 2021-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzeria',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='email',
            field=models.EmailField(blank=True, max_length=245),
        ),
    ]
