# Generated by Django 3.1.7 on 2021-11-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_pizzeria_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='city',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
